### PR TITLE
Update tasks/ubuntu.yml.

### PR DESCRIPTION
**Pull request by mkunin-nvidia**
Adding to tasks/ubuntu.yml proxy configurations in 'enroot deb packages' task. Without this configuration this task fails in environment behind a proxy.

### CODE REVIEW

**Comment by ajdecon** [comment]
@mkunin-nvidia : This is a good change, but because this role is separate from DeepOps it's a little opaque what the `proxy_env` var would do.

For documentation purposes, can you also add the following comment block to `defaults/main.yml` as part of this PR?

```
# Optional: Variables needed for interacting with an HTTP proxy
# (Values are an example)
#
# http_proxy: http://10.0.2.5:3128
# https_proxy: http://10.0.2.5:3128
# no_proxy: localhost,cluster.local,127.0.0.1,::1,10.0.2.10,10.0.2.20,10.0.2.30
# proxy_env:
      # http_proxy: '{{ http_proxy }}'
      # https_proxy: '{{ https_proxy }}'
      # no_proxy: '{{ no_proxy }}'
```

**Comment by ajdecon** [comment]
Also please make the equivalent change for redhat.yml as well.

**Comment by mkunin-nvidia** [comment]
> Also please make the equivalent change for redhat.yml as well.

I don't have environment to test redhat.yml. I can only guess there it should be added.

**Comment by ajdecon** [comment]
That's fine, I have a Red Hat test environment where I can validate that.

**Pull request closed without merging**
